version: "2.4"
services:
  model_service:
    build: ./model_service
    network_mode: "host"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    expose:
      - "5672"
      - "15672"
    network_mode: "host"
    healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "5672" ]
        interval: 10s
        timeout: 10s
        retries: 5

  processing:
    build: ./processing
    network_mode: "host"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
    rabbitmq_data:
    rabbitmq_log:
