version: "3"
services:
  model_service:
    build: ./model_service
    ports:
      - 8000:8000
    network_mode: "host"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    network_mode: "host"

  processing:
    build: ./processing
    ports:
        - 5672:5672
        - 15672:15672
    network_mode: "host"
