# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import contracts_pb2 as contracts__pb2


class ModelServiceStub(object):
    """Model service API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModelServiceAnswer = channel.unary_unary(
                '/contracts.ModelService/GetModelServiceAnswer',
                request_serializer=contracts__pb2.NewsMessage.SerializeToString,
                response_deserializer=contracts__pb2.ModelServiceAnswer.FromString,
                )


class ModelServiceServicer(object):
    """Model service API

    """

    def GetModelServiceAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModelServiceAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelServiceAnswer,
                    request_deserializer=contracts__pb2.NewsMessage.FromString,
                    response_serializer=contracts__pb2.ModelServiceAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Model service API

    """

    @staticmethod
    def GetModelServiceAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contracts.ModelService/GetModelServiceAnswer',
            contracts__pb2.NewsMessage.SerializeToString,
            contracts__pb2.ModelServiceAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
